FROM golang

# RUN apk update && apk add vim git build-base

# RUN go get -u github.com/gin-gonic/gin \
#     && go get -u github.com/jinzhu/gorm \
#     && go get -u github.com/jinzhu/gorm/dialects/mysql \
#     && go get github.com/stretchr/testify \
#     && go get github.com/oxequa/realize 

WORKDIR /go/src/app

RUN go get github.com/pilu/fresh

# # ENV GO111MODULE=on

# # RUN go mod init .

# RUN go get github.com/oxequa/realize
